name: Pull Request Closed

on: 
  pull_request:
    types: [closed]

jobs:
  pr_message:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Envoyer un message
        run: echo "Pull Request mergée"
