name: Workflow Depends

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Premier Job
        run: echo "Premier job exécuté"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Second Job
        run: echo "Second job exécuté après le premier"
