name: Matrix fruits

on: 
  workflow_dispatch:

jobs:
  generer-combinaisons:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [pomme, banane, orange, fraise]
        nom: [Matheo, Alexandre, Francois]
    steps:
      - name: Afficher la combinaison
        run: |
          echo "${{ matrix.nom }} mange une ${{ matrix.fruit }}, et il/elle adore ça !"
        continue-on-error: false 
