name: learn-github-actions
on: 
  push:
    branches:
      - '*' 
  workflow_dispatch: 

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Déclenchement manuel détecté
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "Manuel"

      - name: Déclenchement par push détecté
        if: ${{ github.event_name == 'push' }}
        run: echo "Push"
