name: CI/CD Node.js

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 18, 20]
        include:
          - os: windows-latest
            node-version: 22
        exclude:
          - os: ubuntu-latest
            node-version: 16
          - os: windows-latest
            node-version: 18
          - os: macos-latest
            node-version: 20
      max-parallel: 2

    steps:
      - uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installer les dépendances
        run: npm install

      - name: Construire le projet
        run: npm run build

      - name: Télécharger l'artefact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}-node-${{ matrix.node-version }}
          path: ./dist/

  job-conditionnel:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && matrix.node-version == 18
    needs: build
    steps:
      - name: Télécharger les artefacts
        uses: actions/download-artifact@v3
        with:
          name: build-${{ matrix.os }}-node-${{ matrix.node-version }}

      - name: Simuler le déploiement
        run: echo "Déploiement simulé pour Ubuntu avec Node.js 18"
