name: Next One

on: 
  workflow_run:
    workflows: ["Pull Request Closed"]
    types:
      - completed

jobs:
  next_message:
    runs-on: ubuntu-latest
    steps:
      - name: Envoyer un message
        run: echo "Message du workflow suivant.."
