name: Validation des commits

on:
  push:
    branches:
      - 'features/*'
      - 'hotfix/*'

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Conventional Commits
        uses: webiny/action-conventional-commits@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
