name: workflow_depends

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Tache manuelle
        run: echo "La tache manuelle est faite"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: tâche 2
        run: echo "La tache manuelle et la tache 2 à été réalisée"
